### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by ogbozoyan** [abryant710/auto-codebase-documenter#1]
(venv) ogbozoyan@ogbozoyan ~/IdeaProjects/pabp_business_logic/auto-codebase-documenter$ auto-codebase-documenter
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/auto-codebase-documenter", line 33, in <module>
    sys.exit(load_entry_point('auto-codebase-documenter==1.2', 'console_scripts', 'auto-codebase-documenter')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/auto_codebase_documenter/auto_documenter.py", line 114, in main
    document_code(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/auto_codebase_documenter/auto_documenter.py", line 38, in document_code
    raise ValueError("The OPENAI_KEY environment variable is required to proceed.")
ValueError: The OPENAI_KEY environment variable is required to proceed.

my .env file
OPENAI_KEY=token

i also tried  
OPENAI_KEY="token"

but get same error

**Comment by abryant710** [comment]
The correct format is:

`OPENAI_KEY="token"` within a file called `.env` in the root of the project. You should also run the tool from the root folder of the project. `dotenv` will fallback to Environment Variables on the OS if no `.env` file is detected. 

Also, if you are running it from directly in this codebase, please try `python documenter.py`.

By using `auto-codebase-documenter`, you are using the CLI version which should be used when you import the project using the PyPi package. 

Let me know if you sill have issues.

**Comment by ogbozoyan** [comment]
It didn't helped :( 
May be you passed smth in setup description ?

**Comment by abryant710** [comment]
@ogbozoyan please can you give me some details about the environment you are using? 

If you are using Linux or Mac, please can you install `tree` and run `tree -a` in the directory where you are running the command? Let me know the output.
